[project]
name = "robot-framework-curso"
version = "0.1.0"
description = "Curso - Robot framework"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "requests>=2.34.0",
    "robotframework>=7.4.2",
    "robotframework-browser>=19.15.1",
    "robotframework-dashboard[all]>=2.0.0",
    "robotframework-pabot>=5.2.2",
    "robotframework-requests>=0.9.7",
]
